import test from 'node:test';import assert from 'node:assert/strict';import {HABIT_DEFAULTS as S,habitSettings,drinkAtMouth,DrinkTracker,postureDelta,pitchProxy,cleanDrinkLog} from '../releases/8.1.1/habits.mjs';import {boot} from './harness.mjs';
const det=(type='cup',score=.9)=>({categories:[{categoryName:type,score}],boundingBox:{originX:290,originY:250,width:60,height:100}});
function camera(a){a.state.cameraActive=true;const lm=Array.from({length:478},()=>({x:.5,y:.5,z:0}));for(const [i,x,y]of [[234,.25,.5],[454,.75,.5],[10,.5,.2],[152,.5,.8],[33,.35,.4],[263,.65,.4],[133,.43,.4],[362,.57,.4],[159,.39,.39],[145,.39,.41],[386,.61,.39],[374,.61,.41],[61,.39,.6],[291,.61,.6],[13,.5,.58],[14,.5,.6]])lm[i]={x,y,z:0};a.vision.faceResult={faceLandmarks:[lm],faceBlendshapes:[]};a.processFace();a.vision.objects=[det()];return lm;}
function tick(a,ms){a.advance(ms);a.processFace();a.detectDrink();}
test('Стакан и бутылка классифицируются отдельно у рта',()=>{assert.equal(drinkAtMouth([det()],{x:.5,y:.6},640,480),'cup');assert.equal(drinkAtMouth([det('bottle')],{x:.5,y:.6},640,480),'bottle');});
test('Слабая уверенность, далёкая ёмкость, повреждённый bbox отвергаются',()=>{assert.equal(drinkAtMouth([det('cup',.3)],{x:.5,y:.6},640,480),null);assert.equal(drinkAtMouth([det()],{x:0,y:0},640,480),null);assert.equal(drinkAtMouth([{}],{x:.5,y:.6},640,480),null);});
test('Одно длительное поднесение даёт одно событие',()=>{const t=new DrinkTracker();assert.equal(t.update('cup',0,S),null);assert.equal(t.update('cup',900,S),'cup');for(let n=1000;n<20000;n+=500)assert.equal(t.update('cup',n,S),null);});
test('Смена метки и краткая потеря не создают дубликат',()=>{const t=new DrinkTracker();t.update('cup',0,S);t.update('cup',900,S);assert.equal(t.update('bottle',1200,S),null);t.update(null,1500,S);assert.equal(t.update('cup',1700,S),null);});
test('Новое поднесение после удаления и cooldown засчитывается',()=>{const t=new DrinkTracker();t.update('cup',0,S);t.update('cup',900,S);t.update(null,1000,S);t.update(null,2100,S);t.update('bottle',12000,S);assert.equal(t.update('bottle',12900,S),'bottle');});
test('Углы отклоняются от калибровки, чувствительность меняет порог',()=>{const m={tilt:10,noseY:.5,eyeY:.4,eyeWidth:.3},base={tilt:0,pitch:pitchProxy(m)};assert.equal(postureDelta(m,base,S).bad,false);assert.equal(postureDelta(m,base,{...S,sensitivity:2}).bad,true);assert.equal(postureDelta(null,base,S),null);});
test('Настройки ограничены и не принимают NaN/невалидное время',()=>{const s=habitSettings({roll:0,hold:Infinity,sensitivity:10,windTime:'99:99',drinkConfidence:NaN});assert.equal(s.roll,3);assert.equal(s.hold,3);assert.equal(s.sensitivity,2);assert.equal(s.windTime,'22:00');assert.equal(s.drinkConfidence,.55);});
test('Журнал очищает чужие поля, старые и будущие записи',()=>{const now=Date.now();assert.deepEqual(cleanDrinkLog([{type:'cup',time:now,secret:'x'},{type:'bottle',time:0},{type:'x',time:now},{type:'cup',time:now+120000}],now),[{type:'cup',time:now}]);});
test('Поднесение без распознавания руки записывается и озвучивается через очередь',()=>{const a=boot();camera(a);a.detectDrink();tick(a,900);assert.equal(a.habits.log.length,1);assert.equal(a.waterTotal(),0);assert.ok(a.vision.notices.items.some(x=>x.text.includes('Стакан или кружка')));assert.equal(a.nodes.get('water-confirm').hidden,false);});
test('Журнал переживает перезагрузку, отмена не меняет миллилитры',()=>{const a=boot();camera(a);a.detectDrink();tick(a,900);a.addWater(250);const b=boot(Object.fromEntries(a.data));assert.equal(b.habits.log.length,1);b.nodes.get('habit-undo').click();assert.equal(b.habits.log.length,0);assert.equal(b.waterTotal(),250);});
test('Выключенная вода и несколько лиц не пишут события',()=>{const a=boot();camera(a);a.state.features.water=false;a.detectDrink();tick(a,1000);assert.equal(a.habits.log.length,0);a.state.features.water=true;a.vision.faceCount=2;a.detectDrink();assert.equal(a.habits.log.length,0);});
test('Озвучка включается без Web Audio и использует выбранную громкость',()=>{const a=boot();let message;a.context.speechSynthesis.speak=u=>message=u;a.habits.settings.voiceVolume=.4;a.nodes.get('habit-enable-voice').click();assert.equal(a.state.audioUnlocked,true);assert.equal(message.volume,.4);assert.match(message.text,/Голос включён/);});
test('Выключенная озвучка воды сохраняет статистику без голосового события',()=>{const a=boot();camera(a);a.habits.settings.drinkVoice=false;a.detectDrink();tick(a,900);assert.equal(a.habits.log.length,1);assert.ok(!a.vision.notices.items.some(x=>x.key.startsWith('water:')));});
test('Осанка: порог, выдержка и подавление во время дыхания',()=>{const a=boot();const lm=camera(a);a.nodes.get('calibrate-camera').click();for(let i=0;i<20;i++){a.advance(100);a.processFace();}lm[263].y=.55;a.processFace();a.advance(3100);a.processFace();assert.equal(a.state.postureCorrections,1);a.vision.gates.posture.reset();a.vision.breathing=true;a.advance(31000);a.processFace();assert.equal(a.state.postureCorrections,1);});
test('Напоминание воды срабатывает по интервалу и подавляется в скрытой вкладке',()=>{const a=boot();a.habits.settings.waterReminder=true;a.advance(3600001);a.doc.hidden=true;a.habitRoutineTick();assert.equal(a.vision.notices.items.length,0);a.doc.hidden=false;a.habitRoutineTick();assert.ok(a.vision.notices.items.some(x=>x.key==='water-reminder'));});
test('Вечернее и кофеиновое напоминания выдаются один раз за день',()=>{const a=boot();Object.assign(a.habits.settings,{windDown:true,windTime:'10:00',caffeineReminder:true,caffeineTime:'10:00'});a.habitRoutineTick();assert.equal(a.vision.notices.items.length,2);a.vision.notices.clear();a.advance(20000);a.habitRoutineTick();assert.equal(a.vision.notices.items.length,0);});
test('Дыхание без задержек запускается и безопасно останавливается',()=>{const a=boot();a.nodes.get('habit-slow-breath').click();assert.equal(a.vision.breathing,true);a.advance(4000);a.runInterval(1000);assert.equal(a.nodes.get('breath-phase').innerText,'Выдох');a.stopBreathingGuide();assert.equal(a.vision.breathing,false);});
