import vm from 'node:vm';
import fs from 'node:fs';
import * as analytics from '../releases/8.1.3/analytics.mjs';
import * as habitsModule from '../releases/8.1.3/habits.mjs';
import {SpeechDriver} from '../releases/8.1.3/speech.mjs';
import {RecordedSpeechDriver} from '../releases/8.1.3/recorded-speech.mjs';
export function boot(saved={}){
 let now=Date.parse('2026-09-06T12:00:00Z'),next=1;const timers=new Map(),events=new Map(),data=new Map(Object.entries(saved));
 class Element{
  constructor(id=''){this.id=id;this.style={};this.dataset={};this.children=[];this.value='';this.textContent='';this.innerText='';this.innerHTML='';this.disabled=false;this.hidden=false;this.checked=false;this.listeners={};const c=new Set();this.classList={add:(...s)=>s.forEach(x=>c.add(x)),remove:(...s)=>s.forEach(x=>c.delete(x)),contains:x=>c.has(x),toggle:(x,b)=>{b=b??!c.has(x);b?c.add(x):c.delete(x);return b;}};this.readyState=0;this.videoWidth=640;this.videoHeight=480;this.currentTime=0;}
  addEventListener(k,f){this.listeners[k]=f;}removeEventListener(k){delete this.listeners[k];}setAttribute(k,v){this[k]=v;}getAttribute(k){return this[k];}appendChild(x){this.children.push(x);return x;}append(...x){this.children.push(...x);}prepend(x){this.children.unshift(x);}replaceChildren(...x){this.children=x;}add(x){this.children.push(x);}remove(){}querySelector(){return new Element();}querySelectorAll(){return [];}click(){this.onclick?.({target:this,preventDefault(){}});}dispatchEvent(e){this.listeners[e.type]?.({target:this});}pause(){}async play(){}getContext(){return new Proxy({getImageData:()=>({data:new Uint8ClampedArray(64*48*4)})},{get:(t,k)=>t[k]||(()=>{})});}toDataURL(){return 'data:image/jpeg;base64,AA==';}
 }
 const html=fs.readFileSync(new URL('../ZenFlow-8.1.3.html',import.meta.url),'utf8');const nodes=new Map([...html.matchAll(/id="([^"]+)"/g)].map(m=>[m[1],new Element(m[1])]));
 for(const [id,v]of Object.entries({'breath-cycles-select':'3','vision-feature-filter':'all','vision-event-filter':'all','ambient-volume':'30'}))nodes.get(id).value=v;
 const doc={getElementById:id=>nodes.get(id)||null,createElement:()=>new Element(),querySelectorAll:()=>[],addEventListener:(k,f)=>events.set('doc:'+k,f),body:new Element(),documentElement:new Element(),hidden:false};
 const schedule=(f,ms)=>{const id=next++;timers.set(id,{f,ms});return id;};
 const context={...analytics,...habitsModule,SpeechDriver,RecordedSpeechDriver,document:doc,navigator:{},console,Date:class extends Date{constructor(...a){super(...(a.length?a:[now]));}static now(){return now;}},performance:{now:()=>now},setTimeout:schedule,setInterval:schedule,clearTimeout:i=>timers.delete(i),clearInterval:i=>timers.delete(i),requestAnimationFrame:schedule,cancelAnimationFrame:i=>timers.delete(i),localStorage:{getItem:k=>data.get(k)??null,setItem:(k,v)=>data.set(k,v),removeItem:k=>data.delete(k)},Option:Element,Event:class{constructor(type){this.type=type;}},Blob,URL,Uint8Array,Uint8ClampedArray,atob,confirm:()=>false,location:{reload(){}},addEventListener:(k,f)=>events.set(k,f),speechSynthesis:{speaking:false,speak(){},cancel(){}},SpeechSynthesisUtterance:class{constructor(t){this.text=t;}},innerWidth:1280,innerHeight:800};context.window=context;
 vm.createContext(context);let source=fs.readFileSync(new URL('../releases/8.1.3/app.mjs',import.meta.url),'utf8').replace(/^import .*?;\n/gm,'');source+='\nthis.testAPI={state,vision,habits,speech,enableSpeech,disableSpeech,detectDrink,habitPosture,habitRoutineTick,pomoState,preferences,POMO,addWater,waterTotal,saveData,validateBackup,captureDay,localDay,updateLiveTimer,startPomodoro,pausePomodoro,resetPomodoro,tickPomodoro,startBreathingGuide,stopBreathingGuide,triggerEyeBreak,closeEyeBreak,processFace,processHands,processObjects,processPose,predict,stopCamera,startCamera,performSnapshot,runFeatureChecks,syncFeatureEffects,dispatchNotice,releaseModels,addCaffeine,logMood,setModels:(f,h,o,p)=>{faceLM=f;handLM=h;objectDet=o;poseLM=p;}};';
 vm.runInContext(source,context,{filename:'app.mjs'});return{...context.testAPI,context,nodes,doc,timers,events,data,advance:ms=>now+=ms,runInterval:ms=>{for(const {f,ms:delay}of [...timers.values()])if(delay===ms)f();}};
}
