import test from 'node:test';import assert from 'node:assert/strict';import {boot} from './harness.mjs';
function face(){const a=Array.from({length:478},()=>({x:.5,y:.5,z:0}));for(const [i,x,y]of [[234,.25,.5],[454,.75,.5],[10,.5,.2],[152,.5,.8],[33,.35,.4],[263,.65,.4],[133,.43,.4],[362,.57,.4],[159,.39,.39],[145,.39,.41],[386,.61,.39],[374,.61,.41],[61,.39,.6],[291,.61,.6],[13,.5,.58],[14,.5,.6]])a[i]={x,y,z:0};return a;}
function faceStep(a,lm=face()){a.vision.faceResult={faceLandmarks:lm?[lm]:[],faceBlendshapes:[{categories:[{categoryName:'browInnerUp',score:0},{categoryName:'mouthSmileLeft',score:.8},{categoryName:'mouthSmileRight',score:.8}]}]};a.processFace();}
function active(a){a.state.cameraActive=true;a.vision.lastFrameAt=a.context.Date.now();a.vision.faceCount=1;a.state.lastFaceSeenTs=a.context.Date.now();a.nodes.get('webcam').readyState=2;}

test('Вода: диапазон, добавление, отмена и восстановление',()=>{const a=boot();for(const n of [-1,0,9,2001,NaN,Infinity,2.5])a.addWater(n);assert.equal(a.waterTotal(),0);a.addWater(250);a.addWater(150);assert.equal(a.waterTotal(),400);a.nodes.get('undo-water').click();assert.equal(a.waterTotal(),250);const b=boot(Object.fromEntries(a.data));assert.equal(b.waterTotal(),250);});
test('Кофеин и настроение: добавление и независимая отмена',()=>{const a=boot();a.addCaffeine('coffee');a.addCaffeine('invalid');assert.equal(a.state.caffeineLog.length,1);a.logMood('🙂','Спокойно');a.nodes.get('vision-caffeine-undo').click();assert.equal(a.state.caffeineTotal,0);assert.equal(a.state.moodLog.length,1);a.nodes.get('vision-mood-undo').click();assert.equal(a.state.moodLog.length,0);});
test('Повреждённая копия не перезаписывается',()=>{const a=boot({zenflow_v7:'broken'});a.addWater(100);a.saveData();assert.equal(a.data.get('zenflow_v7'),'broken');});
test('Импорт: схема, числа, дата и опасные ключи',()=>{const a=boot();assert.throws(()=>a.validateBackup({schema:8,days:{}}));assert.throws(()=>a.validateBackup({schema:7,days:{'2026-02-30':{}}}));assert.throws(()=>a.validateBackup({schema:7,days:{[a.localDay()]:{water:Infinity}}}));assert.throws(()=>a.validateBackup(JSON.parse('{"schema":7,"days":{"__proto__":{}}}')));assert.equal({}.polluted,undefined);});
test('Другая вкладка не теряет записи при сохранении',()=>{const a=boot();a.data.set('zenflow_v7','{"schema":7,"days":{}}');a.addWater(100);assert.equal(a.data.get('zenflow_v7'),'{"schema":7,"days":{}}');});
test('Pomodoro: повторный старт, пауза, возобновление, завершение один раз',()=>{const a=boot();a.startPomodoro();const deadline=a.pomoState.deadline;a.startPomodoro();assert.equal(a.pomoState.deadline,deadline);a.advance(10000);a.pausePomodoro();assert.equal(a.pomoState.timeLeft,1490);a.startPomodoro();a.advance(1490000);a.tickPomodoro();a.tickPomodoro();assert.equal(a.state.pomodorosCompleted,1);assert.equal(a.pomoState.isBreak,true);assert.equal(a.pomoState.running,false);});
test('Автопереход Pomodoro включается только явно',()=>{const a=boot();a.vision.settings.autoContinue=true;a.startPomodoro();a.advance(1500000);a.tickPomodoro();assert.equal(a.pomoState.running,true);assert.equal(a.pomoState.isBreak,true);});
test('Фокус: нет камеры, нет лица, скрытая вкладка, зависшие кадры',()=>{const a=boot();a.advance(1000);a.updateLiveTimer();assert.equal(a.state.totalFocusTime,0);active(a);a.setModels({});a.advance(1000);a.updateLiveTimer();assert.equal(a.state.totalFocusTime,1000);a.doc.hidden=true;a.advance(1000);a.updateLiveTimer();assert.equal(a.state.totalFocusTime,1000);a.doc.hidden=false;a.advance(5000);a.updateLiveTimer();assert.equal(a.state.totalFocusTime,1000);});
test('Улыбка: удержание, один счёт, выключатель',()=>{const a=boot();faceStep(a);a.advance(700);faceStep(a);assert.equal(a.state.smiles,1);a.advance(6000);faceStep(a);assert.equal(a.state.smiles,1);faceStep(a,null);a.state.features.smile=false;faceStep(a);a.advance(700);faceStep(a);assert.equal(a.state.smiles,1);});
test('Все датчики лица обрабатывают корректную геометрию без исключений',()=>{const a=boot();faceStep(a);a.nodes.get('calibrate-camera').click();for(let i=0;i<21;i++){a.advance(100);faceStep(a);}assert.equal(a.vision.calibration,null);assert.equal(a.vision.coordinator.errors.length,0);assert.equal(a.vision.coordinator.modules.get('posture').status,'ok');assert.equal(a.vision.coordinator.modules.get('distance').status,'ok');});
test('Приватность: несколько лиц, остановка записи и возврат',()=>{const a=boot();let stops=0;a.vision.recorder={state:'recording',stop(){stops++;this.state='inactive';}};a.vision.faceResult={faceLandmarks:[face(),face()]};a.processFace();a.advance(800);a.processFace();assert.equal(a.vision.privacyActive,true);assert.equal(stops,1);assert.equal(a.performSnapshot('manual'),null);faceStep(a);assert.equal(a.vision.privacyActive,false);});
test('Датчики рук и объектов без входа ждут и не начисляют воду',()=>{const a=boot();a.vision.handResult={landmarks:[]};a.processHands();a.processObjects();assert.equal(a.waterTotal(),0);assert.equal(a.vision.coordinator.errors.length,0);assert.equal(a.vision.coordinator.modules.get('water').status,'waiting');});
test('Телефон: стабильная детекция, cooldown, отключение',()=>{const a=boot();a.vision.objects=[{categories:[{categoryName:'cell phone',score:.9}],boundingBox:{originX:10,originY:10,width:50,height:100}}];a.processObjects();a.advance(700);a.processObjects();assert.equal(a.vision.session.phone,1);a.advance(31000);a.processObjects();assert.equal(a.vision.session.phone,1);assert.equal(a.vision.coordinator.errors.length,0);});
test('Скелет без видимых суставов не считает повторения',()=>{const a=boot();a.vision.exercise=true;a.vision.poseResult={landmarks:[Array.from({length:33},()=>({x:.5,y:.5,visibility:.1}))]};a.processPose();assert.equal(a.state.squats,0);assert.equal(a.vision.session.arms,0);assert.equal(a.vision.coordinator.errors.length,0);});
test('Дыхание не запускает несколько интервалов и блокирует отдых глаз',()=>{const a=boot();a.startBreathingGuide();const n=a.timers.size;a.startBreathingGuide();assert.equal(a.timers.size,n);a.state.lastFaceSeenTs=a.context.Date.now();a.triggerEyeBreak();assert.equal(a.state.eyeBreakActive,false);a.stopBreathingGuide();a.triggerEyeBreak();assert.equal(a.state.eyeBreakActive,true);a.closeEyeBreak();assert.equal(a.state.eyeBreakActive,false);});
test('Отсрочка перерыва и отключение фич очищают конфликтующие состояния',()=>{const a=boot();a.nodes.get('vision-snooze').click();a.state.lastFaceSeenTs=a.context.Date.now();a.triggerEyeBreak();assert.equal(a.state.eyeBreakActive,false);a.vision.privacyActive=true;a.vision.exercise=true;a.state.features.privacy=false;a.state.features.sportMode=false;a.syncFeatureEffects();assert.equal(a.vision.privacyActive,false);assert.equal(a.vision.exercise,false);});
test('Остановка камеры освобождает треки и не ломает Pomodoro',()=>{const a=boot();let stopped=0;active(a);a.nodes.get('webcam').srcObject={getTracks:()=>[{stop(){stopped++;}}]};a.startPomodoro();a.stopCamera();assert.equal(stopped,1);assert.equal(a.state.cameraActive,false);assert.equal(a.pomoState.running,true);});
test('Камера: отсутствие API объясняется в интерфейсе',async()=>{const a=boot();await a.startCamera();assert.match(a.nodes.get('camera-status').innerText,/Камера недоступна/);assert.equal(a.state.cameraActive,false);});
test('Камера: запоздалый stream после отмены немедленно закрывается',async()=>{const a=boot();let resolve,stops=0;a.context.navigator.mediaDevices={getUserMedia:()=>new Promise(r=>resolve=r)};const pending=a.startCamera();a.stopCamera();resolve({getTracks:()=>[{stop(){stops++;}}]});await pending;assert.equal(stops,1);assert.equal(a.state.cameraActive,false);});
test('Ошибка модели лица не мешает объектам и следующему кадру',()=>{const a=boot();active(a);a.nodes.get('webcam').currentTime=1;let objects=0;a.setModels({detectForVideo(){throw Error('face failure');}},null,{detectForVideo(){objects++;return{detections:[]};}});a.predict();assert.equal(objects,1);assert.equal(a.vision.coordinator.modules.get('model-face').status,'error');assert.equal(a.vision.coordinator.modules.get('model-object').status,'ok');});
test('Запись: ручной старт, запрет второго рекордера, остановка и ссылка',()=>{const a=boot();let starts=0,stops=0;a.context.MediaRecorder=class{static isTypeSupported(){return true;}constructor(){this.mimeType='video/webm';this.state='inactive';}start(){starts++;this.state='recording';}stop(){stops++;this.state='inactive';this.ondataavailable({data:new Blob(['test'])});this.onstop();}};active(a);a.nodes.get('vision-record').click();a.nodes.get('vision-record').click();assert.equal(starts,1);a.nodes.get('vision-record-stop').click();assert.equal(stops,1);assert.equal(a.nodes.get('vision-record-download').hidden,false);assert.match(a.nodes.get('vision-record-download').download,/8\.1\.0/);a.nodes.get('vision-clear-gallery').click();assert.equal(a.vision.recordURL,null);});
test('Запись: автоматический предел 60 секунд',()=>{const a=boot();let stopped=false;a.context.MediaRecorder=class{static isTypeSupported(){return true;}constructor(){this.state='inactive';}start(){this.state='recording';}stop(){stopped=true;this.state='inactive';}};active(a);a.nodes.get('vision-record').click();a.runInterval(60000);assert.equal(stopped,true);});
test('Запись: отсутствие MediaRecorder не останавливает дневник',()=>{const a=boot();active(a);a.nodes.get('vision-record').click();assert.equal(a.vision.recorder,null);a.addWater(200);assert.equal(a.waterTotal(),200);});
test('Настройки камеры: невалидные перечисления заменяются значениями по умолчанию',()=>{const a=boot({zenflow_vision_preferences:JSON.stringify({quality:'evil',overlay:'<script>',roi:'x',objectFilter:'x',breakMinutes:900})});assert.equal(a.vision.settings.quality,'balanced');assert.equal(a.vision.settings.overlay,'mesh');assert.equal(a.vision.settings.roi,'all');assert.equal(a.vision.settings.breakMinutes,120);});
test('Экспорт JSON, CSV и диагностики создаёт файлы без ошибки',()=>{const a=boot();a.addWater(250);for(const id of ['export-json','export-csv','vision-export'])assert.doesNotThrow(()=>a.nodes.get(id).click());});
test('Отсутствие Web Audio обрабатывается без исключения',()=>{const a=boot();assert.doesNotThrow(()=>a.context.toggleAmbient('rain'));});
test('Шесть звуков: переключение освобождает источник, громкость симметрична',()=>{const a=boot();let stops=0;const node=()=>({frequency:{value:0},Q:{value:0},gain:{value:0},connect(){},disconnect(){},start(){},stop(){stops++;}});a.context.AudioContext=class{constructor(){this.sampleRate=100;this.state='running';this.destination={};}createBuffer(n,len){return{getChannelData:()=>new Float32Array(len)};}createBufferSource(){return node();}createBiquadFilter(){return node();}createGain(){return node();}createOscillator(){return node();}createChannelMerger(){return node();}};for(const kind of ['rain','ocean','forest','fire','white','binaural'])a.context.toggleAmbient(kind);a.nodes.get('ambient-volume').value=70;a.nodes.get('ambient-volume').dispatchEvent({type:'input'});a.context.toggleAmbient('binaural');assert.equal(stops,7);});
test('Оповещения не прерывают дыхание и удаляются по сроку',()=>{const a=boot();a.vision.notices.push('x','X',a.context.Date.now());a.vision.breathing=true;a.dispatchNotice();assert.equal(a.vision.notices.items.length,1);a.advance(16000);a.vision.breathing=false;a.dispatchNotice();assert.equal(a.vision.notices.items.length,0);});
