import test from 'node:test';import assert from 'node:assert/strict';import fs from 'node:fs';import crypto from 'node:crypto';import {RecordedSpeechDriver,CLIP_TEXT,clipFor} from '../releases/8.1.3/recorded-speech.mjs';import {boot} from './harness.mjs';
function make(){const timers=new Map();let next=0,played=0;const media={src:'',pause(){},play(){played++;return Promise.resolve();}};const d=new RecordedSpeechDriver({media,audioBase:'/audio/',synth:null,Utterance:null,setTimer:(f,ms)=>{timers.set(++next,{f,ms});return next;},clearTimer:n=>timers.delete(n)});return{d,media,timers,get played(){return played;}};}
test('Без SpeechSynthesis проверка голоса проигрывает MP3',()=>{const a=make();assert.equal(a.d.enable('Проверка голоса'),true);assert.equal(a.media.src,'/audio/test.mp3');assert.equal(a.played,1);assert.equal(a.d.route,'recorded');});
test('Для бутылки и стакана используются разные записи',()=>{const a=make();a.d.enable('Бутылка у рта');assert.equal(a.media.src,'/audio/bottle.mp3');a.media.onended();a.d.say('Стакан или кружка у рта');assert.equal(a.media.src,'/audio/cup.mp3');});
test('Событие подтверждается playing, а не только успешным play()',async()=>{const a=make();let started=0;a.d.enable('Стакан у рта',{onStart:()=>started++});await Promise.resolve();assert.equal(started,0);a.media.onplaying();a.media.onplaying();assert.equal(started,1);assert.equal(a.d.status,'speaking');a.media.onended();assert.equal(a.d.status,'ready');});
test('Блокировка autoplay не теряется и предлагает нативную кнопку',async()=>{const a=make();a.media.play=()=>Promise.reject(Object.assign(Error('gesture'),{name:'NotAllowedError'}));a.d.enable('Проверка');await Promise.resolve();assert.equal(a.d.status,'error');assert.match(a.d.message,/▶/);assert.equal(a.d.current,null);});
test('Ошибка файла и таймаут очищают текущее воспроизведение',()=>{const a=make();a.d.enable('Бутылка у рта');a.media.onerror();assert.equal(a.d.status,'error');a.d.enable('Бутылка у рта');[...a.timers.values()].find(t=>t.ms===8000).f();assert.equal(a.d.current,null);});
test('Отменённый play() не может сломать следующую запись',async()=>{const a=make();let reject;a.media.play=()=>new Promise((_,r)=>reject=r);a.d.enable('Бутылка у рта');a.d.stop();a.media.play=()=>Promise.resolve();a.d.enable('Стакан у рта');reject(Error('late'));await Promise.resolve();assert.equal(a.d.status,'starting');assert.equal(a.d.current.clip,'cup');});
test('Нет записи для произвольной фразы — честная ошибка без падения',()=>{const a=make();assert.equal(a.d.enable('Неизвестная строка'),false);assert.match(a.d.message,/нужен речевой движок/);});
test('Карта известных фраз покрывает записи',()=>{assert.equal(clipFor('Вдох'),'inhale');assert.equal(clipFor('Положение головы изменилось'),'posture');assert.equal(clipFor('Телефон остаётся в кадре'),'phone');for(const text of Object.values(CLIP_TEXT))assert.ok(clipFor(text));});
test('Все MP3 существуют, совпадают с манифестом и имеют ненулевую длительность',()=>{const root=new URL('../releases/8.1.3/audio/',import.meta.url),m=JSON.parse(fs.readFileSync(new URL('manifest.json',root),'utf8'));assert.equal(Object.keys(m).length,10);for(const [key,v]of Object.entries(m)){const data=fs.readFileSync(new URL(key+'.mp3',root));assert.equal(data.length,v.bytes);assert.equal(crypto.createHash('sha256').update(data).digest('hex'),v.sha256);assert.ok(v.duration>.3);assert.equal(data.subarray(0,3).toString(),'ID3');}});
test('Событие из приложения проходит через аудиоплеер до подтверждения очереди',()=>{const a=boot();a.enableSpeech();const media=a.nodes.get('speech-player');media.onplaying();media.onended();a.vision.notices.push('water:1','Бутылка у рта',a.context.Date.now());a.dispatchNotice();assert.equal(a.speech.route,'recorded');assert.match(media.src,/bottle.mp3$/);assert.equal(a.vision.notices.items.length,1);media.onplaying();assert.equal(a.vision.notices.items.length,0);});
