import test from 'node:test';import assert from 'node:assert/strict';import {SpeechDriver} from '../releases/8.1.1/speech.mjs';import {boot} from './harness.mjs';
function driver(){let u,next=0,resumes=0;const timers=new Map();const synth={speaking:false,paused:false,speak:x=>u=x,cancel(){},resume(){resumes++;this.paused=false;},getVoices:()=>[{voiceURI:'ru',name:'Русский',lang:'ru-RU',localService:true}]};const d=new SpeechDriver({synth,Utterance:class{constructor(text){this.text=text;}},setTimer:(f,ms)=>{timers.set(++next,{f,ms});return next;},clearTimer:id=>timers.delete(id)});return{d,synth,timers,get utterance(){return u;},get resumes(){return resumes;}};}
test('Статус речи подтверждается onstart, а не включённым переключателем',()=>{const a=driver();a.d.enable('Проверка');assert.equal(a.d.status,'starting');a.utterance.onstart();assert.equal(a.d.status,'speaking');a.utterance.onend();assert.equal(a.d.status,'ready');assert.equal(a.d.current,null);});
test('Поздний русский голос выбирается при следующей фразе',()=>{const a=driver();a.synth.getVoices=()=>[];a.d.enable('Раз');assert.equal(a.utterance.voice,null);a.utterance.onend();a.synth.getVoices=()=>[{voiceURI:'ru',lang:'ru-RU'}];a.d.say('Два');assert.equal(a.utterance.voice.voiceURI,'ru');});
test('Приостановленный синтезатор возобновляется до произнесения',()=>{const a=driver();a.synth.paused=true;a.d.enable('Проверка');assert.equal(a.resumes,1);});
test('Ошибка not-allowed видна, блокировка снимается только повторной проверкой',()=>{const a=driver();a.d.enable('Проверка');a.utterance.onerror({error:'not-allowed'});assert.equal(a.d.status,'error');assert.match(a.d.message,/not-allowed/);assert.equal(a.d.current,null);a.d.enable('Повтор');assert.equal(a.d.status,'starting');});
test('Нет onstart — таймаут сообщает об ошибке и освобождает очередь',()=>{const a=driver();a.d.enable('Проверка');[...a.timers.values()].find(t=>t.ms===5000).f();assert.equal(a.d.status,'error');assert.equal(a.d.current,null);});
test('Нулевая громкость и отсутствие API не выглядят успешным запуском',()=>{const a=driver();assert.equal(a.d.enable('Тест',{volume:0}),false);assert.equal(a.d.status,'error');const b=new SpeechDriver({synth:null,Utterance:null});assert.equal(b.enable('Тест'),false);assert.equal(b.status,'error');});
test('Отменённая фраза не может поздним callback испортить новый статус',()=>{const a=driver();a.d.enable('Раз');const oldStart=a.utterance.onstart;a.d.enable('Два');oldStart();assert.equal(a.d.status,'starting');a.utterance.onstart();assert.equal(a.d.status,'speaking');});
test('Сообщение обнаружения не удаляется до фактического старта речи',()=>{const a=boot();a.enableSpeech();a.speech.current.onstart();a.speech.current.onend();a.vision.notices.push('water:1','Бутылка у рта',a.context.Date.now());a.dispatchNotice();assert.equal(a.vision.notices.items.length,1);assert.equal(a.speech.current.text,'Бутылка у рта');a.speech.current.onstart();assert.equal(a.vision.notices.items.length,0);});
test('Без включённого голоса событие остаётся для повторного запуска',()=>{const a=boot();a.vision.notices.push('water:1','Стакан у рта',a.context.Date.now());a.dispatchNotice();assert.equal(a.vision.notices.items.length,1);assert.equal(a.speech.current,null);});
test('Зависший флаг native speaking не блокирует следующую фразу',()=>{const a=boot();a.enableSpeech();a.speech.current.onend();a.context.speechSynthesis.speaking=true;a.vision.notices.push('water:1','Стакан у рта',a.context.Date.now());a.dispatchNotice();assert.equal(a.speech.current.text,'Стакан у рта');});
test('Озвучка напитков независима от общих подсказок и тихого Pomodoro',()=>{const a=boot();a.enableSpeech();a.speech.current.onend();a.vision.settings.notifications=false;a.vision.settings.quietFocus=true;a.pomoState.running=true;a.vision.notices.push('water:1','Стакан у рта',a.context.Date.now());a.dispatchNotice();assert.equal(a.speech.current.text,'Стакан у рта');});
test('Ошибка речи сохраняет событие и журнал; повторная проверка восстанавливает очередь',()=>{const a=boot();a.enableSpeech();a.speech.current.onend();a.vision.notices.push('water:1','Стакан у рта',a.context.Date.now());a.dispatchNotice();a.speech.current.onerror({error:'audio-busy'});assert.equal(a.vision.notices.items.length,1);a.dispatchNotice();assert.equal(a.speech.current,null);a.nodes.get('speech-recover').click();a.speech.current.onend();a.dispatchNotice();assert.equal(a.speech.current.text,'Стакан у рта');});
