export const HABIT_DEFAULTS={roll:15,pitch:15,sensitivity:1,hold:3,postureCooldown:30,drinkConfidence:.55,drinkHold:.8,drinkCooldown:10,drinkVoice:true,voiceRate:1,voiceVolume:.8,waterReminder:false,waterMinutes:60,windDown:false,windTime:'22:00',caffeineReminder:false,caffeineTime:'16:00'};
export function habitSettings(raw={}){const s={...HABIT_DEFAULTS};if(!raw||typeof raw!=='object')return s;for(const k of Object.keys(s))if(typeof s[k]===typeof raw[k])s[k]=raw[k];for(const [k,min,max]of [['roll',3,45],['pitch',3,45],['sensitivity',.5,2],['hold',1,15],['postureCooldown',10,180],['drinkConfidence',.3,.95],['drinkHold',.3,3],['drinkCooldown',3,60],['voiceRate',.7,1.3],['voiceVolume',0,1],['waterMinutes',15,180]])s[k]=Number.isFinite(s[k])?Math.max(min,Math.min(max,s[k])):HABIT_DEFAULTS[k];for(const k of ['windTime','caffeineTime'])if(!/^([01]\d|2[0-3]):[0-5]\d$/.test(s[k]))s[k]=HABIT_DEFAULTS[k];return s;}
export function drinkAtMouth(detections,mouth,width,height,confidence=.55){if(!mouth||!Number.isFinite(mouth.x)||!Number.isFinite(mouth.y)||width<=0||height<=0)return null;const eligible=[];for(const d of detections||[]){const c=d?.categories?.[0],b=d?.boundingBox;if(!c||!['cup','bottle'].includes(c.categoryName)||!Number.isFinite(c.score)||c.score<confidence||!b||!['originX','originY','width','height'].every(k=>Number.isFinite(b[k]))||b.width<=0||b.height<=0)continue;const x=Math.max(b.originX,Math.min(mouth.x*width,b.originX+b.width)),y=Math.max(b.originY,Math.min(mouth.y*height,b.originY+b.height));const gap=Math.hypot((x-mouth.x*width)/width,(y-mouth.y*height)/height);if(gap<.09)eligible.push({type:c.categoryName,score:c.score,gap});}return eligible.sort((a,b)=>a.gap-b.gap||b.score-a.score)[0]?.type||null;}
export class DrinkTracker{
 constructor(){this.reset();this.last=-Infinity;}
 reset(){this.type=null;this.since=null;this.latched=false;this.absentAt=null;this.lastFrame=null;}
 update(type,now,settings){if(this.lastFrame!==null&&now-this.lastFrame>2000)this.reset();this.lastFrame=now;if(!type){if(this.absentAt===null)this.absentAt=now;if(now-this.absentAt>=1000){this.type=null;this.since=null;this.latched=false;}return null;}this.absentAt=null;if(this.type!==type){if(this.latched)return null;this.type=type;this.since=now;}if(!this.latched&&now-this.since>=settings.drinkHold*1000&&now-this.last>=settings.drinkCooldown*1000){this.latched=true;this.last=now;return type;}return null;}
}
export function pitchProxy(m){return Math.atan2(m.noseY-m.eyeY,m.eyeWidth)*180/Math.PI;}
export function postureDelta(m,baseline,s){if(!m||!baseline)return null;const roll=Math.abs(m.tilt-baseline.tilt),pitch=Math.abs(pitchProxy(m)-baseline.pitch);if(!Number.isFinite(roll)||!Number.isFinite(pitch))return null;return{roll,pitch,bad:roll>s.roll/s.sensitivity||pitch>s.pitch/s.sensitivity};}
export function cleanDrinkLog(raw,now=Date.now()){if(!Array.isArray(raw))return[];return raw.filter(x=>x&&['cup','bottle'].includes(x.type)&&Number.isFinite(x.time)&&x.time<=now+60000&&x.time>now-90*86400000).slice(-5000).map(x=>({type:x.type,time:x.time}));}
